language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
notifications:
  email: false
  slack:
    secure: TKf+ZOtGserrKVwmOXwpu4p5bMdrz7IDj9cK2Ag4WvSRvq+SHiD8U4/Uf7Eae1rudVg47p5HxrNYN3J/IN1z8PuNYRGYYir0xas8kCNARtR+amtGzUd1UvpgALXBiMS9xbVl1i1JBpkoFVR2zmwv2sg+wt4GoyIBEhUw5IFQlMULXurO/pkBqv84OE9Kz5m+csEYI4y6NOxZxKzcEOmvtDCn5RW+Bit2K7J/36pInqtN0ZijsmlTvaMXspP8cWBGkVfLWgxqmIiy6+ce1HWGq3tMdxJ+GHDc/22kfDsa+pb/Lv8peD1zbMZeUII7pkKKzMPk4ELaL5oVgNfmomSg28dPfFbQUPRyYwoN5LzQZarCavP3z8qZ2OlcmC4URjJoBmTV7/OhbBvpehEbvlBEbUpNGRQuirr94XsoM5IlkmTcVE4fzD5YKpnS2O8J8JCAB79dYg7y7Xv9Lw5QaT1fUyQBqMY+ul4E7Lku9UIcQX26lF0E1tQ4X6e0W87GNZvLJs7LWPDcJI5+w9PNx4KeXdQC0+gAzLvaVXXfa/wHd1mTZuXJy/dJBNP/d6oiFO1rHKGv37BedyoAj54t4SY2km42P8G8sthLGP+BYiz/8fB6fRUcT6+xxQjyRgZE4h3QEGeNf1LaCnMQLXKzpcjZeK5L4nX8srpeMVXPeRsMehA=

before_install:
- openssl aes-256-cbc -K $encrypted_3d2a0d7bd1ad_key -iv $encrypted_3d2a0d7bd1ad_iv
  -in $TRAVIS_BUILD_DIR/.travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
install:
- npm i
- npm i -g bower
- npm i grunt-cli
- bower install
script:
- npm run build
before_deploy:
- echo -e "Host christianrebelsky.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  - provider: script
    skip_cleanup: true
    script: sh $TRAVIS_BUILD_DIR/.travis/deploy-production.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: sh $TRAVIS_BUILD_DIR/.travis/deploy-stage.sh
    branches:
      except:
      - master
  - provider: s3
    endpoint: https://ams3.digitaloceanspaces.com
    access_key_id: MWLE3EHXBTGYQK77CBFM
    secret_access_key:
      secure: "aWgzcPIkcfOitFdhsOCbZgFwyC/LQCqIugzpW7tP3yVJXwRl7mSGiwW7awSZDpmch2TcI8uYe5PkPrYb1PZCNqqaDBcjpJ+JvKgV2Pfa5hbAvL7BSw4y5ysjyEPeoNbAkVA0zOncgKh+TcyXMeWLxS6f1nN0AFKuG+PGZg9blbsnml+gK2IdV1olL15J0fbq71iHj7rJerWyETmfLVn9NLUDpryBihdFkqxL/nNhIFfkEGR04n2GnXltOZK0G26SMX8knu+YJNA+cFvwjhCW3+BPe+P7bkgwHT+BNt0HetkiXJZCvoVyVAw/W+5Kb0xIKGNPhmli4LKL9/KwNlFKXHc/jOl9yQtizYGvAe3Mw1u9lwVScE361HNgQeYtUYZt3rmmOuy2m+4uVC2SdKd+wxO/ZIF8xRs3YTocp0RZA5l0+UMELCGI91MwXlRzlWg+T9s87qkVXtI7w4CNHeNhFZSm865tA+niAX/lyLaLSQxenqh2XYJWvpVZ1qQb1u3xgYT5aLMnG4DhyA9666XJHKOp0ZKej6lCdGojetCCH/d8uj5H5FDd9EBi1XJv9Z5zqFDUXuqfHuqdUDIoHmFN0jer1qX20fgvco5/DBt8PueoaY3Ba7pAlgl+spRW2LI3cp3PNvme+l+Mb4giblYGodz9x/Iw6mfDyjhwPslgN2o="
    bucket: cr-asset-space
    skip_cleanup: true
    local_dir: dist
    upload-dir: stage
    on:
      branch: tech/*
  - provider: s3
    endpoint: https://ams3.digitaloceanspaces.com
    access_key_id: MWLE3EHXBTGYQK77CBFM
    secret_access_key:
      secure: "aWgzcPIkcfOitFdhsOCbZgFwyC/LQCqIugzpW7tP3yVJXwRl7mSGiwW7awSZDpmch2TcI8uYe5PkPrYb1PZCNqqaDBcjpJ+JvKgV2Pfa5hbAvL7BSw4y5ysjyEPeoNbAkVA0zOncgKh+TcyXMeWLxS6f1nN0AFKuG+PGZg9blbsnml+gK2IdV1olL15J0fbq71iHj7rJerWyETmfLVn9NLUDpryBihdFkqxL/nNhIFfkEGR04n2GnXltOZK0G26SMX8knu+YJNA+cFvwjhCW3+BPe+P7bkgwHT+BNt0HetkiXJZCvoVyVAw/W+5Kb0xIKGNPhmli4LKL9/KwNlFKXHc/jOl9yQtizYGvAe3Mw1u9lwVScE361HNgQeYtUYZt3rmmOuy2m+4uVC2SdKd+wxO/ZIF8xRs3YTocp0RZA5l0+UMELCGI91MwXlRzlWg+T9s87qkVXtI7w4CNHeNhFZSm865tA+niAX/lyLaLSQxenqh2XYJWvpVZ1qQb1u3xgYT5aLMnG4DhyA9666XJHKOp0ZKej6lCdGojetCCH/d8uj5H5FDd9EBi1XJv9Z5zqFDUXuqfHuqdUDIoHmFN0jer1qX20fgvco5/DBt8PueoaY3Ba7pAlgl+spRW2LI3cp3PNvme+l+Mb4giblYGodz9x/Iw6mfDyjhwPslgN2o="
    bucket: cr-asset-space
    skip_cleanup: true
    local_dir: dist
    upload-dir: production
    on:
      branch: master
