language: node_js
node_js:
  - stable
before_install:
  - openssl aes-256-cbc -K $encrypted_3d2a0d7bd1ad_key -iv $encrypted_3d2a0d7bd1ad_iv
    -in $TRAVIS_BUILD_DIR/.travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
install:
  - npm i
  - npm i -g bower
  - npm i grunt-cli
  - bower install
before_script:
  - echo -e "Host christianrebelsky.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - npm run build
before_deploy:
  - "git push origin master:refs/heads/master"
deploy:
  skip_cleanup: true
  provider: script
  script: sh $TRAVIS_BUILD_DIR/.travis/deploy.sh
  on:
    all_branches: true
