version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/christianrebelsky.com
    steps:
      - checkout
      - attach_workspace:
          at: ~/christianrebelsky.com
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  check_vulnerabilities:
    docker:
      - image: circleci/node:latest
    working_directory: ~/christianrebelsky.com
    steps:
      - attach_workspace:
          at: ~/christianrebelsky.com
      - run: yarn install
      - run: |
          if [ "${CIRCLE_BRANCH}" == "production" ]; then
            yarn validate:dependencies
          else
            yarn validate:dependencies || true
          fi
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/christianrebelsky.com
    steps:
      - attach_workspace:
          at: ~/christianrebelsky.com
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: .
  deployment:
    docker:
      - image: circleci/node:latest
    working_directory: ~/christianrebelsky.com
    steps:
      - attach_workspace:
          at: ~/christianrebelsky.com
      - run: yarn install
      - run:  echo 'deploying branch'
      - add_ssh_keys
      - run: ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
      - run: echo 'THE FINGERPRINT' >> ~/.ssh/known_hosts
      - run:
        - name: upload files to DO
        - command: scp ~/christianrebelsky.com/public ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP:/var/www/christianrebelsky-stage/
workflows:
  version: 2
  test_build:
    jobs:
      - checkout_code
      - check_vulnerabilities:
          requires:
            - checkout_code
      - build:
          requires:
            - checkout_code
      - deployment:
          requires:
           - check_vulnerabilities
           - build
